# Generated by Django 4.2.7 on 2023-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_blog_web', '0002_article_content_article_year_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgThumb',
            field=models.ImageField(blank=True, null=True, upload_to='media_img'),
        ),
    ]
